name: learn-github-actions
on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
      - run: echo "teste github" >> test.txt
      - run: cat test.txt
      - run: sudo apt-get install awscli -y
      - run: aws --version
      - run: aws s3 ls
