name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "teste github" >> test.txt
      - run: cat test.txt
      - run: sudo apt-get install awscli -y
      - run: aws --version
