name: LAB

on:
  push:
    branches: [ main ]

jobs:

  test:

    runs-on: ubuntu-latest
  
    steps:
    - name: Print 
    - run: echo ${{ secrets.teste }}
    - name: Check out code
      uses: actions/checkout@v1
    - run: aws s3 ls
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
